import test from "node:test";
import assert from "node:assert/strict";
import { compileImportedTool, sameToolSemantics } from "../dist/index.js";
const base={name:"lookup",inputSchema:"schema://in",outputSchema:"schema://out",permission:"tool.lookup",sideEffect:"read"};
const policy={allowedPermissions:["tool.lookup"],shadow:true};
test("legacy default and explicit modern preserve typed semantics",()=>{const legacy=compileImportedTool(base,policy);const modern=compileImportedTool({...base,protocol:{era:"modern-2026",capabilities:["server/discover","requestState","input_required","mcp-param-headers","list-cache"],cache:{ttlMs:1000,cacheScope:"private"},authIssuer:"issuer-fixture",authScopes:["tool:read"]}},policy);assert.equal(legacy.ok,true);assert.equal(modern.ok,true);assert.equal(legacy.contract.protocolEra,"legacy-2025");assert.equal(legacy.contract.transport.lifecycle,"initialize");assert.equal(modern.contract.protocolVersion,"2026-07-28");assert.equal(modern.contract.transport.requestModel,"stateless");assert.equal(modern.contract.transport.multiRoundTrip,"input_required");assert.equal(modern.contract.transport.headerRouting,true);assert.equal(modern.contract.cache.ttlMs,1000);assert.equal(sameToolSemantics(legacy.contract,modern.contract),true);});
test("unsupported modern capability fails closed",()=>{const r=compileImportedTool({...base,protocol:{era:"modern-2026",capabilities:["imaginary/method"]}},policy);assert.deepEqual(r,{ok:false,code:"UNSUPPORTED_METHOD",quarantined:true});});
test("local permission and side-effect gates cannot be bypassed",()=>{const denied=compileImportedTool(base,{allowedPermissions:[],shadow:true});assert.equal(denied.ok,false);assert.equal(denied.code,"PERMISSION_DENIED");const write=compileImportedTool({...base,sideEffect:"write"},{...policy,shadow:false});assert.equal(write.ok,false);assert.equal(write.code,"SIDE_EFFECT_DENIED");});
test("modern issuer/scope mismatch is quarantined",()=>{const r=compileImportedTool({...base,protocol:{era:"modern-2026",capabilities:["server/discover"],authIssuer:"issuer-fixture"}},policy);assert.equal(r.ok,false);assert.equal(r.code,"AUTH_MISMATCH");});
